"""Identifiers. Every primary key and public ID is a UUIDv7 generated by the application (data-model.md §1)."""

from __future__ import annotations

import uuid


def new_id() -> uuid.UUID:
    """Return a new UUIDv7: time-ordered, so inserts stay index-friendly and IDs sort by creation time."""
    return uuid.uuid7()


def is_uuid7(value: uuid.UUID) -> bool:
    """True if `value` is an RFC 9562 version 7 UUID."""
    return value.version == 7 and value.variant == uuid.RFC_4122
